In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import pandas as pd
import numpy as np
filename = '../data/pilot01_Phase1_202305251314.tsv'

import pandas as pd
import numpy as np
from io import StringIO

def parse_file(filename):
    # Read file into list of lines
    with open(filename, 'r') as f:
        lines = f.readlines()

    # Extract metadata
    metadata = {}
    for line in lines:
        if line.startswith('Recording'):
            key, value = line.strip().split('\t')
            metadata[key] = value

    # Identify start and end of gaze data and event data
    gaze_data_start = lines.index('Session Start\n') + 1
    gaze_data_end = lines.index('TimeStamp\tEvent\n') - 1
    event_data_start = gaze_data_end + 1
    event_data_end = lines.index('Session End\n') - 1

    # Convert gaze data and event data sections to pandas dataframes
    gaze_data_lines = lines[gaze_data_start:gaze_data_end]
    event_data_lines = lines[event_data_start:event_data_end]

    gaze_data = pd.read_csv(StringIO('\n'.join(gaze_data_lines)), delimiter='\t')
    event_data = pd.read_csv(StringIO('\n'.join(event_data_lines)), delimiter='\t')

    # Convert 'nan' to np.nan
    gaze_data.replace('nan', np.nan, inplace=True)

    return metadata, gaze_data, event_data




# Call the function
metadata, gaze_data, event_data = parse_file(filename)

In [3]:
gaze_data.head()

,TimeStamp,GazePointXLeft,GazePointYLeft,PupilLeft,ValidityLeft,GazePointXRight,GazePointYRight,PupilRight,ValidityRight,GazePointX,GazePointY
0,0.0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN
1,1.7,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN
2,3.3,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN
3,5.0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN
4,6.7,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN